# Generated by Django 6.0.7 on 2026-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajhauser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
