# Generated by Django 6.0.7 on 2026-07-23 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0002_alter_sajhauser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajhauser',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
