# Generated by Django 6.0.7 on 2026-08-09 07:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0003_alter_sajhauser_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajhauser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sajhauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
