# Generated by Django 6.0.7 on 2026-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_alter_sajhauser_email_alter_sajhauser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajhauser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
