# Generated by Django 6.0.7 on 2026-08-09 10:36

import apps.common.validators.phone1
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_sajhauser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajhauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP', validators=[apps.common.validators.phone1.validate_nepal_mobile_number]),
        ),
    ]
