# Generated by Django 6.0.7 on 2026-08-09 10:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0006_alter_sajhauser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sajhauser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
