# Generated by Django 6.0.7 on 2026-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='Hello', editable=False, max_length=20, unique=True),
        ),
    ]
