# Generated by Django 6.0.7 on 2026-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
