"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path

from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Third-party Applications
THIRD_PARTY_APPS = [
    "drf_yasg",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "phonenumber_field",
]

# Local Applications
LOCAL_APPS = [
    # 'apps.common.apps.CommonConfig',  # No need to specify the AppConfig class. Django automatically discovers it from apps.py.so,
    'apps.common',
    'apps.authx',
    'apps.academics.courses',
    'apps.academics.shifts',
    'apps.academics.batches',
    'apps.academics.employees',
    'apps.academics.teachers',
    'apps.academics.students',
    'apps.attendance',
    'apps.learning',
    'apps.notification',
]

INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS
# INSTALLED_APPS.extend(THIRD_PARTY_APPS)
# INSTALLED_APPS.extend(LOCAL_APPS)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must be immediately after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware', #for render deployment
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Cors be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]



WSGI_APPLICATION = 'config.wsgi.application'

AUTH_USER_MODEL = "authx.SajhaUser"  #appName.ModelName


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'

# Media configuration
MEDIA_ROOT = BASE_DIR / 'media'  # To store media files(images, pdf, docx, etc.)
MEDIA_URL = '/media/'  # To access media file to the browser

# Static files configuration (Render Production)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Logger
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamp': {
            'format': '{asctime} {levelname} {message} {lineno} ',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'timestamp',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}

# ---------------------------------------------------------------------
# Django Phone Number Field settings
# ---------------------------------------------------------------------
# Default country region used when validating phone numbers
# without an international country code.
# Example:
# 9841234567 -> +9779841234567
PHONENUMBER_DEFAULT_REGION = "NP"

# Store phone numbers in international E.164 format.
# Example:
# Nepal: +9779841234567
# USA: +14155552671
PHONENUMBER_DB_FORMAT = "E164"



#JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  #15min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # Generate new access and refresh token when refresh API is called
    "ROTATE_REFRESH_TOKENS": True,          #New refresh token(and access token) is created when we hit regenerate token url(TokenRefreshView) 
    # Invalidate old refresh token after generating a new one
    "BLACKLIST_AFTER_ROTATION": True,      #old refresh token will be blacklisted

    # Authorization header format
    "AUTH_HEADER_TYPES": ("Bearer",),
    
}


# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15000), # 15
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # Generate new access and refresh tokens when the refresh endpoint is called
    "ROTATE_REFRESH_TOKENS": True,

    # Blacklist the old refresh token after rotation
    # Blacklist the old refresh token after generating a new one
    "BLACKLIST_AFTER_ROTATION": True,

    # Authorization header format
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": (
                "JWT Authorization header.\n\n"
                "Enter your access token in the following format:\n\n"
                "Bearer <your_access_token>"
            ),
        }
    },
}